### ISSUE TITLE
RouteGen tests failing on Ubuntu 18 & 20 - out of memory

### ISSUE THREAD

**Issue by tril0byte** [hyperboria/cjdns#196]
Running test RouteGen_test----- cjdns memory snapshot -----
RouteGen_test.c:117 [13016] bytes
  RouteGen_test.c:107 [104216] bytes
  | RouteGen.c:538 [881736] bytes
  | | RouteGen.c:312 [104] bytes at [0x557fa6c05770]
[...lots of lines...]
  RouteGen_test.c:117 [224] bytes at [0x557fa6ac05f0]
totalBytes [1048800] remaining [8]
----- end cjdns memory snapshot -----
ArrayList.c:72 Fatal error: [Out of memory, limit exceeded.]

Ubuntu 18.04.2 and 20.04 have this same problem building from master.
I worked around this on Ubuntu 18.04.2 using cjdns v20.2, but v20.2 does not build on Ubuntu 20.04 due to other problems including incompatible system headers.

**Comment by tril0byte** [comment]
complete output of running "./do 2>&1 > ubuntu-cjdns-build.txt"-
[ubuntu-cjdns-build.txt](https://github.com/hyperboria/bugs/files/4536287/ubuntu-cjdns-build.txt)
